---
title: "Calculating p-value functions"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Calculating p-value functions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, message=FALSE}
library(tidyverse)
library(flipr)
```

```{r fig.width=6, out.width="100%"}
x1 <- rnorm(10)
x2 <- rnorm(10, 3)

grid_size <- 100
B <- 100

data_t <- tibble(
  delta = seq(0, 6, length.out = grid_size),
  null_spec = map(delta, ~ function(y) {y - .x}),
  two_tail = map_dbl(
    .x = null_spec,
    .f = two_sample_pf,
    x = x1,
    y = x2,
    statistic = stat_t,
    seed = 1234,
    B = B,
    alternative = "two_tail"
  ),
  left_tail = map_dbl(
    .x = null_spec,
    .f = two_sample_pf,
    x = x1,
    y = x2,
    statistic = stat_t,
    seed = 1234,
    B = B,
    alternative = "left_tail"
  ),
  right_tail = map_dbl(
    .x = null_spec,
    .f = two_sample_pf,
    x = x1,
    y = x2,
    statistic = stat_t,
    seed = 1234,
    B = B,
    alternative = "right_tail"
  )
) %>%
  select(-null_spec) %>%
  pivot_longer(-delta)

data_t %>%
  ggplot(aes(delta, value, color = name)) +
  geom_line() +
  labs(
    title = "P-value function for the mean difference", 
    subtitle = "t-statistic", 
    x = expression(delta), 
    y = "p-value", 
    color = "Type"
  ) +
  geom_hline(
    yintercept = 0.05,
    color = "black",
    linetype = "dashed"
  ) +
  geom_vline(
    xintercept = mean(x2) - mean(x1),
    color = "black"
  ) +
  geom_vline(
    xintercept = stats::t.test(x2, x1, var.equal = TRUE)$conf.int,
    color = "black",
    linetype = "dashed"
  ) +
  scale_y_continuous(breaks = seq(0, 1, by = 0.05), limits = c(0, 1))
```
