# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

stat_student_impl <- function(distanceMatrix, firstGroupIndices, secondGroupIndices) {
    .Call(`_flipr_stat_student_impl`, distanceMatrix, firstGroupIndices, secondGroupIndices)
}

stat_fisher_impl <- function(distanceMatrix, firstGroupIndices, secondGroupIndices) {
    .Call(`_flipr_stat_fisher_impl`, distanceMatrix, firstGroupIndices, secondGroupIndices)
}

stat_bg_impl <- function(distanceMatrix, firstGroupIndices, secondGroupIndices) {
    .Call(`_flipr_stat_bg_impl`, distanceMatrix, firstGroupIndices, secondGroupIndices)
}

stat_energy_impl <- function(distanceMatrix, firstGroupIndices, secondGroupIndices, alphaValue = 1L) {
    .Call(`_flipr_stat_energy_impl`, distanceMatrix, firstGroupIndices, secondGroupIndices, alphaValue)
}

stat_cq_impl <- function(similarityMatrix, firstGroupIndices, secondGroupIndices) {
    .Call(`_flipr_stat_cq_impl`, similarityMatrix, firstGroupIndices, secondGroupIndices)
}

getElement <- function(distObject, rowIndex, colIndex) {
    .Call(`_flipr_getElement`, distObject, rowIndex, colIndex)
}

